# Configuration for Alacritty, the GPU enhanced terminal emulator.

import = [
    # "/Users/robin/.config/alacritty/themes/themes/github_light.toml",
    "/Users/robin/.config/alacritty/themes/themes/github_dark.toml",
]

[cursor.style]
blinking = "On"
shape = "Underline"

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 13.0

[font.normal]
family = "MesloLGS NF"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Buttonless"
opacity = 0.98

[window.padding]
x = 10
y = 10

