## which search mode to use
## possible values: prefix, fulltext, fuzzy, skim
# search_mode = "fuzzy"

## which filter mode to use
## possible values: global, host, session, directory
filter_mode = "global"

## which style to use
## possible values: auto, full, compact
style = "full"

## Defaults to true. If enabled, upon hitting enter Atuin will immediately execute the command. Press tab to return to the shell and edit.
# This applies for new installs. Old installs will keep the old behaviour unless configured otherwise.
enter_accept = true

local_timeout = 60

inline_height = 15
history_format = "{command}\t{duration}"

filter_mode_shell_up_key_binding = "session"
prefers_reduced_motion = true
